# generated by datamodel-codegen:
#   filename:  format.json
#   timestamp: 2024-07-15T19:30:12+00:00

from __future__ import annotations

from typing import Annotated, Any, Mapping

from pydantic import BaseModel, Field


class Configuration(BaseModel):
    specification: Mapping[str, Any]
    settings: Mapping[str, Any]


class Root(BaseModel):
    kind: Annotated[str, Field(max_length=32)]
    name: Annotated[str, Field(max_length=64)]
    version: Annotated[str, Field(max_length=10)]
    description: Annotated[str, Field(None, max_length=2000)]
    configuration: Configuration
